### PR TITLE
Remove BCC functionality

### PR DESCRIPTION
**Pull request by ousmanedev**
Fixes https://github.com/magicbell-io/magicbell-ruby/issues/10

### CODE REVIEW

**Comment by unamashana** [comment]
@ousmanedev Thanks a lot for this! Do you think it's possible to deprecate the functionality before we remove it? This might be a breaking change for some people.

**Comment by ousmanedev** [comment]
Hello @unamashana 

I think we can safely remove it, as long as the changes get released under a new [major version](https://semver.org/#spec-item-6). It will not affect the current "users" until they upgrade to the newest version (2.0.0).

**Comment by unamashana** [comment]
@ousmanedev I thought some more about it. I think we should print a change message on bundle install when installing 2.0.0. Something like what HTTParty does - https://brandonhilkert.com/blog/ruby-gem-post-install-message/. This is a breaking change and users need to be warned about it. We can't expect them to know and reliability is the #1 feature :)

Thanks!

**Comment by ousmanedev** [comment]
@unamashana , I totally agree. Is there an announcement  somewhere, about the BCC feature deprecation ? I could take inspiration from that, to add a post install message.

Also, what do you think about adding a [CHANGELOG](https://keepachangelog.com/en/1.0.0/), like it's done [here](https://github.com/jnunemaker/httparty/blob/master/Changelog.md) ?

**Comment by unamashana** [comment]
@ousmanedev Changelog is a great idea. Let's start with this release!

How about this message? We never announced this because technically the BCC feature still works - we just don't want new users to use it :)

```
*** Breaking Change:: The 2.0.0 release removes the BCC functionality. Please update your MagicBell integration to use the API for creating notifications or downgrade to 1.0.4 ***
```

**Comment by ousmanedev** [comment]
@unamashana , I've added the suggested post-install message, with a bit of formatting.

See how it shows up in my terminal:
Screenshot 2021-06-23 at 15 09 07

**Pull request merged**
